-- AlterTable
ALTER TABLE `tasks`
    ADD COLUMN `taskSource` ENUM('CUSTOM', 'GITHUB_ISSUE', 'UPWORK', 'FREELANCER', 'ISSUEHUNT', 'BOUNTYSOURCE') NOT NULL DEFAULT 'CUSTOM',
    ADD COLUMN `sourceUrl` VARCHAR(500) NULL,
    ADD COLUMN `sourceRepo` VARCHAR(255) NULL,
    ADD COLUMN `sourceIssueNumber` INTEGER NULL;
