ALTER TABLE `tasks`
    MODIFY `taskSource` ENUM('CUSTOM', 'GITHUB_ISSUE', 'UPWORK', 'FREELANCER', 'ISSUEHUNT', 'BOUNTYSOURCE', 'ERDOS_PROBLEM') NOT NULL DEFAULT 'CUSTOM',
    ADD COLUMN `sourceMetadata` JSON NULL;
