export const ROLE_NAME_CANDIDATES: Record<string, string[]> = {
  OWNER: [
    "Augustus",
    "Li Shimin",
    "George Washington",
    "Lee Kuan Yew",
    "Deng Xiaoping",
    "Steve Jobs",
    "Jeff Bezos",
    "Elon Musk",
    "Henry Ford",
    "Thomas Edison",
    "Akio Morita",
    "Walt Disney",
    "Andrew Carnegie",
    "John D. Rockefeller",
    "Sam Walton",
    "Peter Thiel",
    "Bill Gates",
    "Mark Zuckerberg",
    "Jack Ma",
    "Ren Zhengfei",
    "Masayoshi Son",
    "Ray Dalio",
    "Warren Buffett",
    "Charlie Munger",
    "Jensen Huang",
    "Lisa Su",
    "Satya Nadella",
    "Andy Grove",
    "Reed Hastings",
    "Howard Schultz",
    "Indra Nooyi",
    "Mary Barra",
    "Sheryl Sandberg",
    "Meg Whitman",
    "Lou Gerstner",
    "Jack Welch",
    "Alfred Sloan",
    "Konosuke Matsushita",
    "Soichiro Honda",
    "Richard Branson",
    "Oprah Winfrey",
    "Arianna Huffington",
    "Brian Chesky",
    "Patrick Collison",
    "Tobi Lutke",
    "Travis Kalanick",
    "Daniel Ek",
    "Reid Hoffman",
    "Marc Benioff",
    "Michael Dell"
  ],

  LEAD_AGENT: [
    "Julius Caesar",
    "Alexander the Great",
    "Napoleon Bonaparte",
    "Vladimir Lenin",
    "Winston Churchill",
    "Donald Trump",
    "Dwight D. Eisenhower",
    "George Washington",
    "Abraham Lincoln",
    "Theodore Roosevelt",
    "Franklin D. Roosevelt",
    "Charles de Gaulle",
    "Otto von Bismarck",
    "Lee Kuan Yew",
    "Margaret Thatcher",
    "Nelson Mandela",
    "Mahatma Gandhi",
    "Martin Luther King Jr.",
    "Mustafa Kemal Ataturk",
    "Genghis Khan",
    "Qin Shi Huang",
    "Liu Bang",
    "Li Shimin",
    "Zhu Yuanzhang",
    "Kangxi Emperor",
    "Catherine the Great",
    "Peter the Great",
    "Elizabeth I",
    "Queen Victoria",
    "Meiji Emperor",
    "Sun Yat-sen",
    "Chiang Kai-shek",
    "Mao Zedong",
    "Deng Xiaoping",
    "Zhou Enlai",
    "Angela Merkel",
    "Barack Obama",
    "Ronald Reagan",
    "John F. Kennedy",
    "Richard Nixon",
    "Tony Blair",
    "Narendra Modi",
    "Shinzo Abe",
    "Volodymyr Zelenskyy",
    "Simon Bolivar",
    "Joan of Arc",
    "Hannibal Barca",
    "Scipio Africanus",
    "Saladin",
    "Tokugawa Ieyasu"
  ],

  PLANNER_AGENT: [
    "Sun Tzu",
    "Zhuge Liang",
    "Zhang Liang",
    "John von Neumann",
    "Dwight D. Eisenhower",
    "Carl von Clausewitz",
    "Alfred Thayer Mahan",
    "B. H. Liddell Hart",
    "Peter Drucker",
    "W. Edwards Deming",
    "Frederick Winslow Taylor",
    "Henry Mintzberg",
    "Michael Porter",
    "Igor Ansoff",
    "Clayton Christensen",
    "Jay Forrester",
    "Herbert Simon",
    "Norbert Wiener",
    "Claude Shannon",
    "Alan Turing",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Ken Thompson",
    "Dennis Ritchie",
    "Leslie Lamport",
    "Grace Hopper",
    "Margaret Hamilton",
    "Fred Brooks",
    "Linus Torvalds",
    "Guido van Rossum",
    "Andrew Ng",
    "Geoffrey Hinton",
    "Yoshua Bengio",
    "Donald Norman",
    "Andrej Karpathy",
    "Jeff Dean",
    "Demis Hassabis",
    "Fei-Fei Li",
    "Barbara Liskov",
    "Frances Allen",
    "Seymour Cray",
    "Vannevar Bush",
    "J. C. R. Licklider",
    "Marvin Minsky",
    "George Marshall",
    "Thomas Schelling",
    "Henry Kissinger",
    "Zbigniew Brzezinski",
    "Hyman Rickover",
    "Omar Bradley"
  ],

  WORKER_AGENT: [
    "Linus Torvalds",
    "Grace Hopper",
    "Margaret Hamilton",
    "Andrej Karpathy",
    "Yann LeCun",
    "Han Xin",
    "Huo Qubing",
    "Zhao Yun",
    "Lu Ban",
    "Alan Turing",
    "Dennis Ritchie",
    "Ken Thompson",
    "Bjarne Stroustrup",
    "Guido van Rossum",
    "James Gosling",
    "Brendan Eich",
    "Tim Berners-Lee",
    "John Carmack",
    "John Romero",
    "Jeff Dean",
    "Sanjay Ghemawat",
    "Rob Pike",
    "Brian Kernighan",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Barbara Liskov",
    "Frances Allen",
    "Ada Lovelace",
    "Claude Shannon",
    "Niklaus Wirth",
    "Rich Hickey",
    "Martin Fowler",
    "Kent Beck",
    "Ward Cunningham",
    "Robert C. Martin",
    "Brian Chesky",
    "Patrick Collison",
    "Tobi Lutke",
    "Drew Houston",
    "Guillermo Rauch",
    "DHH",
    "Fabrice Bellard",
    "George Hotz",
    "Vitalik Buterin",
    "Satoshi Nakamoto",
    "Yukihiro Matsumoto",
    "Rasmus Lerdorf",
    "Larry Wall",
    "Miguel de Icaza",
    "Werner Vogels"
  ],

  FINDING_VALIDATOR: [
    "Richard Feynman",
    "Karl Popper",
    "Carl Sagan",
    "Marie Curie",
    "Isaac Newton",
    "Galileo Galilei",
    "Francis Bacon",
    "Ada Lovelace",
    "Florence Nightingale",
    "John Tukey",
    "Ronald Fisher",
    "Nate Silver",
    "Daniel Kahneman",
    "Amos Tversky",
    "Thomas Bayes",
    "Pierre-Simon Laplace",
    "Claude Shannon",
    "Norbert Wiener",
    "Donald Knuth",
    "Leslie Lamport",
    "Barbara McClintock",
    "Rosalind Franklin",
    "Louis Pasteur",
    "Robert Koch",
    "Jonas Salk",
    "James Randi",
    "Michael Faraday",
    "Niels Bohr",
    "Max Planck",
    "Albert Einstein",
    "Enrico Fermi",
    "Paul Dirac",
    "Stephen Hawking",
    "Jane Goodall",
    "Charles Darwin",
    "Di Renjie",
    "Bao Zheng",
    "Hai Rui",
    "Song Ci",
    "Li Changyu",
    "John Snow",
    "Rachel Carson",
    "Elizabeth Loftus",
    "David Spiegelhalter",
    "Judea Pearl",
    "Andrew Gelman",
    "Edward Tufte",
    "Nassim Nicholas Taleb",
    "Phil Tetlock",
    "Atul Gawande"
  ],

  REPORT_REVIEWER: [
    "Peter Drucker",
    "W. Edwards Deming",
    "Edward Tufte",
    "Warren Buffett",
    "Charlie Munger",
    "William Zinsser",
    "George Orwell",
    "William Strunk Jr.",
    "E. B. White",
    "Doris Kearns Goodwin",
    "Walter Isaacson",
    "Barbara Minto",
    "Tom Peters",
    "Clayton Christensen",
    "Michael Porter",
    "Jim Collins",
    "Ben Horowitz",
    "Andy Grove",
    "Lou Gerstner",
    "Jack Welch",
    "Indra Nooyi",
    "Satya Nadella",
    "Sheryl Sandberg",
    "Mary Barra",
    "Meg Whitman",
    "Ray Dalio",
    "Seth Godin",
    "David Ogilvy",
    "Rosabeth Moss Kanter",
    "Henry Mintzberg",
    "Daniel Kahneman",
    "Nassim Nicholas Taleb",
    "Atul Gawande",
    "Malcolm Gladwell",
    "Steven Pinker",
    "Yuval Noah Harari",
    "Jared Diamond",
    "Niall Ferguson",
    "Paul Graham",
    "Marc Andreessen",
    "Ben Thompson",
    "Tyler Cowen",
    "Noah Smith",
    "Matt Levine",
    "John McPhee",
    "Robert Caro",
    "David Halberstam",
    "Gay Talese",
    "Joan Didion",
    "Susan Sontag"
  ],

  REPORT_WRITER: [
    "Sima Qian",
    "Herodotus",
    "Thucydides",
    "Walter Isaacson",
    "Doris Kearns Goodwin",
    "Ban Gu",
    "Chen Shou",
    "Edward Gibbon",
    "Will Durant",
    "Barbara Tuchman",
    "Robert Caro",
    "David McCullough",
    "Niall Ferguson",
    "Jared Diamond",
    "Yuval Noah Harari",
    "Michael Lewis",
    "Malcolm Gladwell",
    "Steven Pinker",
    "Atul Gawande",
    "John McPhee",
    "George Orwell",
    "Ernest Hemingway",
    "Joan Didion",
    "Susan Sontag",
    "Tom Wolfe",
    "Gay Talese",
    "Truman Capote",
    "Hunter S. Thompson",
    "Hannah Arendt",
    "Rebecca Solnit",
    "Rachel Carson",
    "Jane Jacobs",
    "James Gleick",
    "Nicholas Carr",
    "Clay Shirky",
    "Paul Graham",
    "Ben Thompson",
    "Matt Levine",
    "Tyler Cowen",
    "Noah Smith",
    "David Brooks",
    "Fareed Zakaria",
    "Thomas Friedman",
    "Anne Applebaum",
    "Masha Gessen",
    "Liang Qichao",
    "Lu Xun",
    "Hu Shih",
    "Qian Zhongshu",
    "Wang Xiaobo"
  ],

  SECURITY_AUDITOR: [
    "Bruce Schneier",
    "Kevin Mitnick",
    "Dan Kaminsky",
    "Mudge",
    "Gene Spafford",
    "Cliff Stoll",
    "Whitfield Diffie",
    "Martin Hellman",
    "Ron Rivest",
    "Adi Shamir",
    "Leonard Adleman",
    "Phil Zimmermann",
    "Ross Anderson",
    "Matt Blaze",
    "Joanna Rutkowska",
    "Halvar Flake",
    "Dino Dai Zovi",
    "Charlie Miller",
    "Chris Valasek",
    "Katie Moussouris",
    "Alex Stamos",
    "Tavis Ormandy",
    "Michal Zalewski",
    "H. D. Moore",
    "Fyodor Vaskovich",
    "Runa Sandvik",
    "Elias Levy",
    "Peiter Zatko",
    "Jennifer Granick",
    "Moxie Marlinspike",
    "Daniel J. Bernstein",
    "Nadia Heninger",
    "Cynthia Dwork",
    "Shafi Goldwasser",
    "Silvio Micali",
    "David Chaum",
    "Dorothy Denning",
    "Peter G. Neumann",
    "Eugene Kaspersky",
    "Mikko Hypponen",
    "Brian Krebs",
    "Katie Hafner",
    "Marcus Ranum",
    "John McAfee",
    "Robert Morris",
    "Ken Thompson",
    "Dennis Ritchie",
    "Richard Stallman",
    "Theo de Raadt",
    "Poul-Henning Kamp"
  ],

  REVIEW_AGENT: [
    "Linus Torvalds",
    "Barbara Liskov",
    "Leslie Lamport",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Ken Thompson",
    "Dennis Ritchie",
    "Bjarne Stroustrup",
    "Martin Fowler",
    "Kent Beck",
    "Robert C. Martin",
    "Ward Cunningham",
    "Michael Feathers",
    "Grady Booch",
    "Ivar Jacobson",
    "James Gosling",
    "Guido van Rossum",
    "Brendan Eich",
    "Rob Pike",
    "Brian Kernighan",
    "Jeff Dean",
    "Sanjay Ghemawat",
    "John Carmack",
    "Fabrice Bellard",
    "Rich Hickey",
    "Yukihiro Matsumoto",
    "Rasmus Lerdorf",
    "Larry Wall",
    "Miguel de Icaza",
    "Werner Vogels",
    "Brian Goetz",
    "Joshua Bloch",
    "Douglas Crockford",
    "Anders Hejlsberg",
    "Niklaus Wirth",
    "David Parnas",
    "Fred Brooks",
    "Margaret Hamilton",
    "Grace Hopper",
    "Frances Allen",
    "Ada Lovelace",
    "Alan Turing",
    "Claude Shannon",
    "John Backus",
    "Jean Sammet",
    "Mary Shaw",
    "Nancy Leveson",
    "Jeannette Wing",
    "Bret Victor",
    "Casey Muratori"
  ],

  INTEGRATOR_AGENT: [
    "Tim Berners-Lee",
    "Vint Cerf",
    "Robert Kahn",
    "Linus Torvalds",
    "James Gosling",
    "Ken Thompson",
    "Dennis Ritchie",
    "Rob Pike",
    "Brian Kernighan",
    "Margaret Hamilton",
    "Grace Hopper",
    "Ada Lovelace",
    "J. C. R. Licklider",
    "Vannevar Bush",
    "Douglas Engelbart",
    "Alan Kay",
    "Steve Jobs",
    "Bill Gates",
    "Andy Grove",
    "Satya Nadella",
    "Jeff Bezos",
    "Elon Musk",
    "Jensen Huang",
    "Lisa Su",
    "Werner Vogels",
    "Urs Hoelzle",
    "Jeff Dean",
    "Sanjay Ghemawat",
    "Guido van Rossum",
    "Bjarne Stroustrup",
    "Anders Hejlsberg",
    "Brendan Eich",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Leslie Lamport",
    "Barbara Liskov",
    "Martin Fowler",
    "Kent Beck",
    "Robert C. Martin",
    "Ward Cunningham",
    "Otto von Bismarck",
    "Zheng He",
    "Zhang Qian",
    "Ibn Battuta",
    "Marco Polo",
    "George Marshall",
    "Henry Kissinger",
    "Zhou Enlai",
    "Deng Xiaoping",
    "Lee Kuan Yew"
  ],

  LEGAL_AGENT: [
    "Hammurabi",
    "Justinian I",
    "Cicero",
    "John Marshall",
    "Ruth Bader Ginsburg",
    "Oliver Wendell Holmes Jr.",
    "Louis Brandeis",
    "Thurgood Marshall",
    "Antonin Scalia",
    "Sandra Day O'Connor",
    "Earl Warren",
    "William Blackstone",
    "Edward Coke",
    "Cesare Beccaria",
    "Montesquieu",
    "Hugo Grotius",
    "Jeremy Bentham",
    "John Austin",
    "H. L. A. Hart",
    "Ronald Dworkin",
    "Hans Kelsen",
    "Lon Fuller",
    "Roscoe Pound",
    "Joseph Story",
    "Benjamin Cardozo",
    "Learned Hand",
    "Felix Frankfurter",
    "Sonia Sotomayor",
    "Elena Kagan",
    "John Roberts",
    "Clarence Darrow",
    "Alan Dershowitz",
    "Amal Clooney",
    "Geoffrey Robertson",
    "Philippe Sands",
    "Louis Henkin",
    "Raphael Lemkin",
    "Navi Pillay",
    "Kofi Annan",
    "Eleanor Roosevelt",
    "Bao Zheng",
    "Di Renjie",
    "Shang Yang",
    "Han Fei",
    "Li Kui",
    "Zhang Juzheng",
    "Sir Edward Grey",
    "Robert Jackson",
    "Sally Yates",
    "Merrick Garland"
  ]
};

export const GENERAL_AGENT_NAMES: string[] = [
  "Alex",
  "Morgan",
  "Taylor",
  "Jordan",
  "Casey",
  "Riley",
  "Avery",
  "Quinn",
  "Cameron",
  "Drew",
  "Sam",
  "Jamie",
  "Robin",
  "Charlie",
  "Skyler",
  "Reese",
  "Parker",
  "Logan",
  "Harper",
  "Emerson",

  "Leo",
  "Max",
  "Jack",
  "Ethan",
  "Noah",
  "Liam",
  "Mason",
  "Owen",
  "Lucas",
  "Henry",
  "Theo",
  "Milo",
  "Felix",
  "Oscar",
  "Arthur",
  "Caleb",
  "Isaac",
  "Eli",
  "Nolan",
  "Julian",

  "Iris",
  "Luna",
  "Maya",
  "Nora",
  "Ella",
  "Ava",
  "Mia",
  "Zoe",
  "Chloe",
  "Aria",
  "Lily",
  "Ruby",
  "Grace",
  "Hazel",
  "Ivy",
  "Vera",
  "Clara",
  "Alice",
  "Emma",
  "Sofia",

  "Kai",
  "Ren",
  "Tao",
  "Jun",
  "Lin",
  "Chen",
  "Ming",
  "Wei",
  "Han",
  "Shen",
  "Yun",
  "Lei",
  "Bo",
  "Feng",
  "Jin",
  "Hao",
  "Long",
  "Qin",
  "Yi",
  "Zhen",

  "Aiden",
  "Blake",
  "Cole",
  "Dean",
  "Finn",
  "Gavin",
  "Hayden",
  "Jude",
  "Kian",
  "Levi",
  "Miles",
  "Nico",
  "Orion",
  "Pierce",
  "Rowan",
  "Sage",
  "Troy",
  "Wyatt",
  "Xander",
  "Zane",

  "Ada",
  "Belle",
  "Cora",
  "Daisy",
  "Eden",
  "Flora",
  "Gemma",
  "Holly",
  "Isla",
  "Juno",
  "Kira",
  "Lyra",
  "Mira",
  "Nova",
  "Opal",
  "Pearl",
  "Rhea",
  "Selene",
  "Tessa",
  "Willa",

  "Atlas",
  "Apollo",
  "Ares",
  "Hermes",
  "Orpheus",
  "Phoenix",
  "Titan",
  "Helios",
  "Ajax",
  "Odin",
  "Thor",
  "Loki",
  "Freya",
  "Athena",
  "Hera",
  "Diana",
  "Venus",
  "Minerva",
  "Gaia",
  "Nyx",

  "Byte",
  "Cipher",
  "Vector",
  "Kernel",
  "Pixel",
  "Cache",
  "Token",
  "Prompt",
  "Lambda",
  "Nova",
  "Echo",
  "Quest",
  "Orbit",
  "Rocket",
  "Scout",
  "Pilot",
  "Forge",
  "Spark",
  "Nexus",
  "Flux",

  "Ace",
  "Blade",
  "Bolt",
  "Dash",
  "Drift",
  "Edge",
  "Flash",
  "Ghost",
  "Hawk",
  "Hunter",
  "Knight",
  "Ranger",
  "Raven",
  "Shadow",
  "Storm",
  "Striker",
  "Viper",
  "Wolf",
  "Falcon",
  "Arrow",

  "Anchor",
  "Bridge",
  "Cedar",
  "Cloud",
  "Comet",
  "Copper",
  "Delta",
  "Ember",
  "Forest",
  "Harbor",
  "Indigo",
  "Jasper",
  "Meadow",
  "Onyx",
  "River",
  "Silver",
  "Stone",
  "Summit",
  "Vale",
  "Winter"
];