ALTER TABLE `tasks`
    MODIFY `taskSource` ENUM('CUSTOM', 'GITHUB_ISSUE', 'HACKERONE', 'UPWORK', 'FREELANCER', 'ISSUEHUNT', 'BOUNTYSOURCE', 'ERDOS_PROBLEM') NOT NULL DEFAULT 'CUSTOM';

ALTER TABLE `raw_tasks`
    MODIFY `source` ENUM('GITHUB_ISSUE', 'HACKERONE_PROGRAM', 'UPWORK', 'ISSUEHUNT') NOT NULL;

ALTER TABLE `task_generator_runs`
    MODIFY `type` ENUM('FETCH_GITHUB', 'FETCH_HACKERONE', 'SCORE', 'PUBLISH', 'SCORE_AND_PUBLISH') NOT NULL;
